### ISSUE TITLE
UST stuck in Kernel

### ISSUE THREAD

**Issue by helunc** [0xNODES/community#11]
UST can be deposited the yearn-aave strategy  without issues, can also withdraw fine from the yearn-aave strategy, but cannot withdraw from the kernel. It is stuck there. 

When trying to withdrawal the UST, it says "There was an error, check your browser's console log for more details"

**Comment by jensonb** [comment]
hey @helunc,

Sorry for the slow response on here, I'm in charge of managing the community feedback here now and we are tying to become much more responsive.

The withdraw issue you were facing has been resolved, and I have confirmed in a local simulated test that your account should be able with withdraw some or all of the UST assets you have deposited in the system.

Thank you so much for your patience as we worked to resolve that issue. Thanks as well for being a user of 0xNODES, a community member, and for providing us with the bug report :)

**Comment by 0xnode1** [comment]
confirmed w end user, wd completed.
