### ISSUE TITLE
Compromised MetaMask

### ISSUE THREAD

**Issue by jgweir** [0xNODES/community#12]
Dear 0xNodes Team,

I recently bought and staked XIOT token onto the 0xNodes platform.  I was aware XIOT would be locked indefinitely.
Recently I believe the MetaMask account that I used to buy and stake my XIOT tokens was compromised from a phishing hack (I believe they have my password AND secret recovery phrase).

I have moved all the assets from this wallet to a new wallet, except my current bag of XIOT tokens.

Is there any way to be able to declare/swap my current wallet on 0xNodes for another wallet ?
At the moment I still monitor the compromised wallet, and I am accruing BIOS.

After discussing with Owl (telegram), he suggested I post this here.

Any help would be deeply appreciated.
Kind Regards

**Comment by tomxnodes** [comment]
resolved :)

**Comment by jgweir** [comment]
Thanks!
