### ISSUE TITLE
Support for different web3 wallets like Framewallet

### ISSUE THREAD

**Issue by Mafaku** [0xNODES/community#20]
_Fwd: from Cryptomooniac 11 via Discord_

The dapp does not work with Frame wallet even when connected / injected as Metamask (assets keep loading). It is a pity, since I've ditched Metamask for good and dApps should not be building for Metamask specific behaviour but fully compatible with EIP-1193. 

Furthermore, a little bit more clarity in the dApp UI would help a lot. Users don't really understand what the strategies are, what they should be deposited and what APRs should they expect. I know that some of this info (not all) is on 0xnodes.live but still. 

Some friendly feedback. Hope it is taken as such.

**Comment by gitlappi** [comment]
This should be merged with #24 since it is the same issue.

**Comment by Mafaku** [comment]
Merged with #24
