### ISSUE TITLE
Kernel initialise not inviting

### ISSUE THREAD

**Issue by honderd** [0xNODES/community#25]
When you open the website you get a blank screen and can only enter if you connect your metamask, that is not user friendly UX, especially for new users who first want to check out what OX is all about :-)
<img width="946" alt="Screenshot" src="https://user-images.githubusercontent.com/95744336/145178248-18cd6a54-96a6-4da8-a253-24cf748d16df.png">

**Comment by jensonb** [comment]
hey @honderd thanks for the heads up on this! Yes we do need a fix on this, basically the solution (as you found out) is that the app will load once you sign up to metamask, or disable metamask in the tab (although of course you won't be able to use the system until you connect).

Thanks for the reminder on this one, I'm going to pass it on for our UI team to have a look at. I'll pass on more information about our progress on this one.

**Comment by tomxnodes** [comment]
closing, as this is now tracked internally. Thank you for the suggestion, @honderd
