### ISSUE TITLE
User not able to remove USDT from KERNEL via Manage Assets tab

### ISSUE THREAD

**Issue by Mafaku** [0xNODES/community#26]
Fwd: from Christian via Telegram

![image](https://user-images.githubusercontent.com/95633034/145666697-b167c343-cac1-42b5-9aa2-c6b1213adc74.png)

![image](https://user-images.githubusercontent.com/95633034/145666703-b755a3bc-e0f9-4033-9968-d258bca94f1e.png)

**Comment by Jugyman** [comment]
any updates on this?? dealing with the same issue !!!! Urgent

**Comment by tomxnodes** [comment]
@Mafaku this @Jugyman this is veryold, please try again or close this if you already succeeded. System ahs been massively upgraded since then.

**Comment by Mafaku** [comment]
Fixed
