### ISSUE TITLE
Matic Deposits not showing in Kernel

### ISSUE THREAD

**Issue by Jugyman** [0xNODES/community#32]
Tried to deposit Matic to the kernel today, and funds are not showing.  This is the transaction https://polygonscan.com/tx/0x1df24f818ee3965c90aebd25a644b232cb0dcf773c252213b67458c7efc16f66
when raising the issue on the discord another member had the same issue. 

I was definitely on the correct website!

**Comment by tomxnodes** [comment]
This is eligible for an award. Definitely the UI did not help you out here. The UI has been fixed for crossing chains.

**Comment by Jugyman** [comment]
What is happening with this bounty please Tom?
