### ISSUE TITLE
Not displaying amount in dollars when depositing or withdrawing (minor issue)

### ISSUE THREAD

**Issue by LateralNZ** [0xNODES/community#4]
[](url
![Withdraw](https://user-images.githubusercontent.com/93115655/138644870-29057c36-fb59-4194-ae07-d3f01ecc3ff9.PNG)
![deposit](https://user-images.githubusercontent.com/93115655/138644873-813c5097-23b7-43f9-8c9e-601e03a64eac.PNG)
)

**Comment by tomxnodes** [comment]
The council has determined to display values in native token, ( ETH, MATIC, AVAX, etc)
