### ISSUE TITLE
Emissions not working for SLP tokens in the bios.emitter function

### ISSUE THREAD

**Issue by AugustG98** [0xNODES/community#6]
Hey, August also known as Viva from the TG and discord here again.

 So like we talked about in the chats earlier.. just putting this info in here too. we've noticed there's been a few reportings that there seems to be no emissions for the SLP tokens in the bios emitter which is kinda strange. But most likely the explanation is very simple. 

It's been noticed looking at the kernel babe0 contract in events and logs... SLP weight is 221/1346 but the team made the SLP token addition into the bios.emitter function AFTER the epoch was already restarted so new weights don't apply to this epoch (current_epoch is 3). This is the same that happened the first time the weights were off and that they were changed mid-epoch. So it's likely the changes that were made on the weights doesn't apply until the new epoch.

**Comment by tomxnodes** [comment]
thanks @AugustG98 we have started multiple epochs since then, so closing.
