### ISSUE TITLE
Issue in new Litepaper

### ISSUE THREAD

**Issue by Fruhji** [0xNODES/community#9]
<img width="557" alt="bsc" src="https://user-images.githubusercontent.com/44861470/139587780-ee3d6ab2-9e39-470c-a6e8-f8cb765e5ffd.png">

On the new Litepaper found at https://0xnodes.io/docs (https://0xnodes.io/assets/documents/LITEPAPER.pdf) there is TVL of BSC displayed 3 times. One should be Ethereum Mainnet and the other maybe KuCoin? 

So Binance Smart Chain TVL15.87B Ethereum Mainnet TVL?B Kucoin TVL?B

**Comment by 0xHarrington** [comment]
This is still the case.

**Comment by tomxnodes** [comment]
Closing, @Fruhji  and @MattAHarrington as we don't intend to fix. We will address in subsequent litepapers, this one is here for posterity. :)
